### ISSUE TITLE
Bug: Clicking a username within the bio of a profile "fidget" updates profile details but not space details

### ISSUE THREAD

**Issue by willyogo** [blankdotspace/space-system#222]
Steps to repro:
1. Visit a space with a bio that contains usernames (ie. https://warpcast.com/xenbh.eth)
2. Click the username in the bio

Expected result:
1. user navigates to that username's space and sees their theme, fidgets, and profile details

Actual result:
1. only the profile details are updated

AC:
1. When a user clicks a username in the bio of a profile fidget, the user is navigated to that username's space and sees their theme, fidgets, and profile details

**Comment by hiporox** [comment]
This is actually not quite what is happening, but it appears to be this way due to most Farcaster users not having a customized space and us not showing a loading signal when the users change

**Comment by willyogo** [comment]
> This is actually not quite what is happening, but it appears to be this way due to most Farcaster users not having a customized space and us not showing a loading signal when the users change

are you sure? i was just able to repro and the new spaces haven't loaded after a minute. 
<img width="1574" alt="image" src="https://github.com/Nounspace/nounspace.ts/assets/26232238/c06ea513-199d-441e-8736-1463aedd33fb">

the example space i used in the steps to repro does not actually have a username in its bio, i got that wrong. this user does though https://www.nounspace.com/s/183aaros.eth

**Comment by hiporox** [comment]
Using the PR I have, it seems to be fixing the issue
