### ISSUE TITLE
Bug: User unable to drag fidget + fidget starts vibrating

### ISSUE THREAD

**Issue by willyogo** [blankdotspace/space-system#225]
A few users have reported an inability to drag a fidget, particularly the feed fidget.

Clue: when this occurs, the fidget will start vibrating too.

AC: 
1. Reliability of fidget drag-ability is improved

[User report in discord](https://discord.com/channels/1224471875023802521/1251186884726493225/1258118323539804180)

https://github.com/Nounspace/nounspace.ts/assets/26232238/8aa67017-40e0-4708-90d4-83c08e85c8cc

**Comment by hiporox** [comment]
This is likely fixed in #233, but we should double check once it releases

**Comment by willyogo** [comment]
fixed in v0.0.3

h/t @raygbiv for testing
