### ISSUE TITLE
Bug: User unable to resize gallery fidget without immediate black screen error

### ISSUE THREAD

**Issue by raygbiv** [blankdotspace/space-system#230]
Initially resizing gallery fidgets was working, but now consistently redirects page to black screen with "Application error: a client-side exception has occurred (see the browser console for more information)." Seems to only happen with resizing gallery fidget specifically. 

Steps to reproduce:
1. create gallery fidget
2. drag frame to grid, expand to 3x3 or 4x4
3. if it allows initial expansion, try to resize again

acceptance criteria: Users are able to resize gallery fidgets without error

https://github.com/Nounspace/nounspace.ts/assets/174657321/5a8343b3-68fc-4110-91ac-628be2f61315

**Comment by willyogo** [comment]
i haven't been able to repro this yet, but @raygbiv consistently can. we'll give it another try after this next round of fixes goes out to see if that clears anything up.

**Comment by taylorwilco** [comment]
I am able to reproduce this same bug. Every time I go to resize it , it crashes and gives the same error

**Comment by willyogo** [comment]
likely related to https://github.com/Nounspace/nounspace.ts/issues/265

**Comment by willyogo** [comment]
Update: By deleting all of the fidgets from their spaces and starting from scratch, neither Cam nor Ray are reproducing this issue. Gonna close it for now until we hear reports from other users that are running into this.
