### ISSUE TITLE
Bug (staging): App crashes when dragging the governance fidget onto a space

### ISSUE THREAD

**Issue by willyogo** [blankdotspace/space-system#237]
Currently in the canary vercel environment, the app crashes due to a minified react error and/or client-side exception that occurs when the governance fidget is dragged onto a space.

Steps to repro:
1. In the canary environment, edit a space and drag the governance fidget to the grid

AC:
1. Users are able to drag any fidget(s) onto the space without experiencing any errors

![image](https://github.com/Nounspace/nounspace.ts/assets/26232238/7855e2d1-0b9c-43d5-9fe2-de0f833bebb9)

**Comment by nounspaceryan** [comment]
I rebased canary to include this hotfix (55aeafee24bd0d4934db1c1a05f386fc887a97a0) from main which resolves this. Closing this issue.
