### ISSUE TITLE
Cast: When a user casts, close the cast modal and show a toast notification "cast successfully sent"

### ISSUE THREAD

**Issue by willyogo** [blankdotspace/space-system#258]
Currently, when a user casts, the cast modal stays open and users have reported accidentally double casting because they didn't realize their cast was sent.

AC:
1. When a user successfully casts, the cast modal closes and a toast message is displayed at the bottom of the window "Cast created successfully"

**Comment by sktbrd** [comment]
https://github.com/Nounspace/nounspace.ts/pull/428
