### ISSUE TITLE
Bug: Investigate app consistently crashing for user

### ISSUE THREAD

**Issue by willyogo** [blankdotspace/space-system#265]
A user reported consistent app crashing on their space. Prior to the app crashing, they reported "whenever I drag one out to my space/grid it just disappears again. whenever I drag one out to my space/grid it just disappears again. I just tried reloading the page and now the app crashes as soon as it loads."

"there's one request that 404s and after that it crashes"
![image](https://github.com/user-attachments/assets/96933d7c-9984-4c8b-8c63-5f5845aba2da)

Steps to repro:
1. Visit https://www.nounspace.com/s/datadanne.eth

AC:
1. https://www.nounspace.com/s/datadanne.eth
2. stretch: the issue that caused datadanne to not be able to add fidgets to his space and/or caused his space to crash is fixed

**Comment by hiporox** [comment]
[Fix to make the space load is live](https://github.com/Nounspace/nounspace.ts/commit/f2f10d65e2d35419fea2a66d5831ab246013e6ea), but the underlying cause of what is saving data without the proper data is still up in the air. I think we fundamentally need to change the structure of space data. I will write thoughts up for architecture later

**Comment by willyogo** [comment]
likely related to https://github.com/Nounspace/nounspace.ts/issues/230

**Comment by willyogo** [comment]
We received another report from a user whose space is crashing consistently: https://www.nounspace.com/s/sebastianlehrer

this is a high value user so if we could hotfix their space that would be awesome 🙏

**Comment by willyogo** [comment]
Closing for now until we hear other reports
