### ISSUE TITLE
Bug: Users are unable to select a channel from the Cast modal

### ISSUE THREAD

**Issue by willyogo** [blankdotspace/space-system#275]
Currently users are unable to select a channel when casting

Steps to repro:
1. Attempt to cast to a channel

Expected result:
1. Users can search for channels by name and select any channel in the dropdown by clicking it

Actual:
1. User cannot input text into the search field nor select channels from the dropdown

AC:

- [ ] Users can search for channels by name and select any channel in the dropdown by clicking it 

Update: @sktbrd investigated and traced the issue back to the Mod protocol API we're using which is no longer being maintained. in order to fix this, we need to rebuild the cast modal using Neynar API and our own UI

[Mockup](https://www.figma.com/design/p7kcxeBG7v4goZwmhLCoYc/Nounspace-App-(Copy)?node-id=1089-1792&t=M6d3MnlxJcaxj8Nr-0)

after a PR for the above AC has been opened, please prioritize the following improvements to the cast modal
- [ ] Users can upload an image to imgur and include in their cast (https://apidocs.imgur.com/#c85c9dfc-7487-4de2-9ecd-66f727cf3139)
- [x] #418

**Comment by sktbrd** [comment]
@r4topunk how is that one going ?
