### ISSUE TITLE
Add tooltips on hover to the buttons displayed over an actively selected fidget

### ISSUE THREAD

**Issue by willyogo** [blankdotspace/space-system#276]
As platform admins, we want to clarify the purpose of each button displayed over an actively selected fidget

AC:
1. When a user hovers over the 'Stash' icon, display "Stash in Fidget Tray" tooltip
2. When a user hovers over the 'X' icon, display "Delete Fidget" tooltip
3. If a user clicks the 'X' icon and hovers over the '<-' icon, display "Cancel" ; if they hover over the 'X' icon, display "Confirm Delete"

**Comment by sktbrd** [comment]
https://github.com/Nounspace/nounspace.ts/pull/285
