### ISSUE TITLE
Add zoom setting to Swap and iFrame fidgets

### ISSUE THREAD

**Issue by willyogo** [blankdotspace/space-system#326]
As a user, I want to be able to adjust the zoom % for the swap and iFrame fidgets, from 50% to 200%

AC:
1. A slider is added to the iFrame and Swap Fidget settings for zoom
2. Default for iFrame is 100% (right in the middle), default for Swap is 80%

**Comment by sktbrd** [comment]
https://github.com/Nounspace/nounspace.ts/pull/329
