### ISSUE TITLE
Gallery Fidget Improvements

### ISSUE THREAD

**Issue by willyogo** [blankdotspace/space-system#335]
AC:
1. New setting: URL - Fidget owner can add a URL to the gallery fidget that opens when clicked
2. New setting: Scale - Fidget owner can adjust scale of image via slider in settings

**Comment by sktbrd** [comment]
https://github.com/Nounspace/nounspace.ts/pull/338

**Comment by sktbrd** [comment]
waiting for review

**Comment by sktbrd** [comment]
https://github.com/Nounspace/nounspace.ts/pull/410 merged this one
