### ISSUE TITLE
Display 'wtf is nouns?' tooltip when user hovers over ⌐◨-◨  logo

### ISSUE THREAD

**Issue by willyogo** [blankdotspace/space-system#360]
As a user, I want to fall down the rabbit hole of nouns when exploring nounspace.

![Image](https://github.com/user-attachments/assets/b1be5103-22dc-49bf-a617-09a3066ef901)

AC:
1. When a user hovers over the ⌐◨-◨ logo, the 'wtf is nouns?' tooltip is displayed
2. if a user clicks the tooltip, nouns.wtf opens in a new tab

**Comment by sktbrd** [comment]
https://github.com/Nounspace/nounspace.ts/pull/366
