### ISSUE TITLE
Theme Editor UI Updates

### ISSUE THREAD

**Issue by willyogo** [blankdotspace/space-system#361]
Assorted polishes to the Theme Editor UI:
- [x] Tab order is updated so Style is the first tab and Fonts is the second tab.
- [x] The theme templates dropdown is moved into the Theme Card, and a book icon is added to the right (alternative icon idea: pallete?). If a user clicks the Theme Card or book icon, they see the dropdown with theme templates
- [x] A subtitle is added to Edit Theme: "Select a template or [learn how to customize](https://nounspace.notion.site/Step-by-step-instructions-f760579615b44efb84dcc30647a87e61?pvs=4)"

![Image](https://github.com/user-attachments/assets/3e62069c-911c-4276-bd95-da76ca76afb4)

**Comment by sktbrd** [comment]
![Image](https://github.com/user-attachments/assets/3f05ebb5-ae49-4dce-925f-7909ddf59655)


the book icon takes a fair portion of the menu space when the dropdown is open
