### ISSUE TITLE
Add default text fidget to all user's Homebase Feed Tab

### ISSUE THREAD

**Issue by willyogo** [blankdotspace/space-system#377]
As a user, I want to see instructions on how to customize spaces as soon as I log in to nounspace for the first time.

By adding a pre-populated Text Fidget, we can give users a clear onboarding guide right inside the app. They won't even need to switch screens! :D

Copy for the instructions as well as details for the fidget style: https://hackmd.io/@Pmj-d7FpTRaIOeoZfXggmQ/SkpnMLTsR/edit

AC:
1. A Text Fidget with the attached copy and style settings is added to the bottom right section of the Feed Tab on the homebase of all new/all users who have not yet edited their homebase

![image](https://github.com/user-attachments/assets/7ce6503d-e7ac-437d-9db2-e8e21ec08220)

**Comment by sktbrd** [comment]
Done
