### ISSUE TITLE
Bug: warpcast onchain auth requests are not being sponsored

### ISSUE THREAD

**Issue by willyogo** [blankdotspace/space-system#389]
More context in discord: https://discord.com/channels/1224471875023802521/1224498450482331743/1279807702851260520

AC:
1. When a user authorizes nounspace as a signer in Warpcast, their registration costs are sponsored by nounspace

**Comment by sktbrd** [comment]
![image](https://github.com/user-attachments/assets/4d365b90-63c3-4d21-a367-3a4b8bc129fc)

<img width="357" alt="image" src="https://github.com/user-attachments/assets/38d8c033-6eae-4130-acf2-65298184ffee">

**Comment by sktbrd** [comment]
https://github.com/Nounspace/nounspace.ts/pull/414
