### ISSUE TITLE
Polish login modal UI

### ISSUE THREAD

**Issue by willyogo** [blankdotspace/space-system#411]
Current UI:

![image](https://github.com/user-attachments/assets/c0dd23e9-787c-4413-8ac4-66b8f456d1b2)

Plz make it look like this:
![image](https://github.com/user-attachments/assets/b11c0150-c383-47ca-8dab-1af1a9650575)

**Comment by sktbrd** [comment]
https://github.com/Nounspace/nounspace.ts/pull/417
