### ISSUE TITLE
Bug: Reply casts don't cast

### ISSUE THREAD

**Issue by willyogo** [blankdotspace/space-system#427]
Steps to repro:
Try to reply to a cast

Expected result: Cast is broadcasted for farcaster network

Actual result: Cast disappears forever and is not broadcasted

AC:
1. When a user replies to a cast on nounspace, their reply is broadcasted to the farcaster network

**Comment by sktbrd** [comment]
<img width="1119" alt="image" src="https://github.com/user-attachments/assets/f498f0fc-1463-420f-9d13-0be66879e228">

Found the error

**Comment by sktbrd** [comment]
fixed at https://github.com/Nounspace/nounspace.ts/pull/428

**Comment by sktbrd** [comment]
https://github.com/Nounspace/nounspace.ts/pull/428
