### ISSUE TITLE
Bug: Clicking paintbrush on Notification tab causes sidebar to disappear

### ISSUE THREAD

**Issue by willyogo** [blankdotspace/space-system#446]
Steps to repro:
1. Visit https://www.nounspace.com/notifications
2. Click the paintbrush

AC:
1. Paintbrush is not displayed on the Notifications page / users can't attempt to enter edit mode from the notifications page

**Comment by sktbrd** [comment]
https://github.com/Nounspace/nounspace.ts/pull/447
