### ISSUE TITLE
Bug: Music search

### ISSUE THREAD

**Issue by willyogo** [blankdotspace/space-system#483]
Pasting a youtube link no longer works for selecting songs. Additionally, if you try searching for multiple songs, eventually search will stop working and no results will be displayed.

AC:
1. Users can select music by pasting Youtube link
2. When a user types into the search box, they see song suggestions (this works at first, but if you keep trying different songs, eventually it will stop loading)

**Comment by willyogo** [comment]
Update: if search still works, pasting a song link will sometimes result in the song showing up in search results. this breaks once search stops working though, and shouldn't require searching (should just autopopulate from the link like it used to)

**Comment by sktbrd** [comment]
I think that got solved in the middle of last R4tos PR

<img width="233" alt="image" src="https://github.com/user-attachments/assets/2bcf01c2-4a59-42ff-b3f4-bdb0868e0eb6" />
