### ISSUE TITLE
Track all new tokens deployed by Clanker

### ISSUE THREAD

**Issue by willyogo** [blankdotspace/space-system#528]
As platform admins, we want to track all tokens deployed by Clanker so we can display the cast that deployed the token in the Pinned Cast fidget and so we can enable the deployer of the token to claim the Token Space.

AC:
1. When a token is deployed by Clanker, the parent cast as well as the parent caster's FID and verified addresses are stored in a database.

**Comment by hiporox** [comment]
This shouldn't be a necessary thing at all. We can have a default pre-populated set of information for any Clanker CA that is entered. The user who's cast deployed the token will be enabled to click the edit button

**Comment by willyogo** [comment]
you're right about not needing this for generating the token spaces, which is awesome. tom is also set to respond to all new clanker deployments.

i think we'll still want this to display the [directory of clanker tokens](https://github.com/Nounspace/nounspace.ts/issues/536), but perhaps there's an alternative for this too. either will close this issue for now
